language: ruby
sudo: required
services:
  - docker
cache:
  - bundler
rvm:
  - 2.3
env:
  global:
    - KITCHEN_YAML=.kitchen.docker.yml
  matrix:
    - CHEF_VERSION=12 KAFKA_VERSION=0.8.1.1 SCALA_VERSION=2.9.2 KAFKA_MD5=7541ed160f1b3aa1a5334d4e782ba4d3
    - CHEF_VERSION=12 KAFKA_VERSION=2.0.0 SCALA_VERSION=2.11 KAFKA_CTRL_SHUTDOWN=true
    - CHEF_VERSION=13 KAFKA_VERSION=2.0.0 SCALA_VERSION=2.11 KAFKA_SHA512=a8cbc1663fcaf4fd4473eb551d43bd48266be518032c8234826ed1061e569ec3ea9a7ce02606f211908e356eafa3bf214e0f23250d0dbd08a4279047ba49dc73
    - CHEF_VERSION=13 KAFKA_VERSION=2.0.0 SCALA_VERSION=2.11 CHEF_CHANNEL=current
install: travis_wait bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
script: bundle exec kitchen test --destroy=always
matrix:
  fast_finish: true
  allow_failures:
    - env: CHEF_VERSION=13 KAFKA_VERSION=2.0.0 SCALA_VERSION=2.11 CHEF_CHANNEL=current
  include:
    - sudo: false
      env: []
      rvm: 2.3
      script: bundle exec rake test
